config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'blogs#index'

  resources :blogs

  resources :comments, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: {minimum: 250}

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blogs
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :find_blog, only: [:show, :edit, :update, :destroy]

	def index
		@blogs = Blog.all.order(created_at: :desc)
	end

	def show
		#@blog = Blog.find(params[:id])
	end

	def new
		if user_signed_in?
			@blog = Blog.new
		else
			redirect_to new_user_session_path
		end
	end

	def create
		@blog = Blog.new(blog_params)
		if @blog.save
			redirect_to blogs_path, notice: "El post fue adicionado correctamente"
		else
			render :new
		end
	end

	def edit
		#@blog = Blog.find(params[:id])
	end

	def update
		#@blog = Blog.find(params[:id])
		if @blog.update(blog_params)
			redirect_to blogs_path, notice: "El post fue actualizado exitosamente"
		else
			render :edit
		end
	
	end

	def destroy
		#blog = Blog.find(params[:id])
		if @blog.destroy
			redirect_to blogs_path, notice: "El post fue eliminado exitosamente"
		end
	end

	protected
	def blog_params
		params.require(:blog).permit(:title,:body,:user_id)
	end

	private
	def find_blog
		@blog = Blog.find(params[:id])
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.new(comment_params)
		if @comment.save
			redirect_to blog_path(@comment.blog_id)
		end
	end

	protected
		def comment_params
			params.require(:comment).permit(:user_id,:blog_id,:comment_body)
		end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def markdown(text)
	    options = {
	      filter_html:     true,
	      hard_wrap:       true,
	      link_attributes: { rel: 'nofollow', target: "_blank" },
	      space_after_headers: true,
	      fenced_code_blocks: true
	    }

	    extensions = {
	      autolink:           true,
	      superscript:        true,
	      disable_indented_code_blocks: true
	    }

	    renderer = Redcarpet::Render::HTML.new(options)
	    markdown = Redcarpet::Markdown.new(renderer, extensions)

	    markdown.render(text).html_safe
	end

	def time_ago(created_time)
		mins = ((Time.now - created_time) / 60).to_i
		case
			when mins < 0 
				"EN EL FUTURO"
			when mins == 0 
				"un momento"
			when mins == 1 
				"1 minuto"
			when mins >  1 && mins < 60
				mins.to_s + " minutos"
			when mins >=  60 && mins < 120
				"alrededor de 1 hora"
			when mins >=  120 && mins < 1440
				(mins / 60).to_s + " horas"
			when mins >= 1440 && mins < 2880
				"1 día"
			when mins >= 2880
				(mins / (60 * 24)).to_s + " días"
		end
		
	end

end

app/helpers/blogs_helper.rb
module BlogsHelper

	def form_title
		@blog.new_record? ? "Nuevo Post" : "Modificar Post"
	end
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1><%= form_title %></h1>

      <div>
        <ul id="error_frame">
          <li class="error_msg" id="err_title">Título no puede estar en blanco</li>
          <li class="error_msg" id="err_body01">Cuerpo no puede estar en blanco</li>
          <li class="error_msg" id="err_body02">Cuerpo es demasiado corto (250 caracteres mínimo)</li>
        </ul>
      </div>

      <%= form_for @blog do |b| %>
        <div class="form-group">
          Título: <%= b.text_field :title, class: "form-control input-lg", placeholder: "Ingresa el título del Post" %>
        </div>
        <div class="form-group">
          Cuerpo: <%= b.text_area :body, rows: 10, class: "form-control input-lg", placeholder: "Ingresa el cuerpo del Post" %>
        </div>
        	<%= b.hidden_field :user_id, value: current_user.id %>
        <div>
          <%= b.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/edit.html.erb
<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<table class="table">
				<% @blogs.each do |b| %>
					<tr>
						<td>
							<h1><%= link_to b.title, blog_path(b.id) %></h1>
							<h3><small><%= b.comments.count %> comentario(s)</small></h3>
							<h3><small>Publicado por <%= b.user.email %> hace <%= time_ago(b.created_at) %></small></h3>
							<% if b.body.length > 250 %>
							<%	puntos = "..." %>
							<% else %>
							<% 	puntos = "" %>
							<% end %>
							<p><%= markdown(b.body[0,249] + puntos) %></p>
							<% if user_signed_in? &&
								current_user.id == b.user_id %>
								<p>
									<span class="glyphicon glyphicon-pencil"><%= link_to "Editar", edit_blog_path(b.id) %></span>
									<span class="glyphicon glyphicon-trash"><%= link_to "Eliminar", b, method: :delete, data: { confirm: "Realmente quieres eliminar este post?" } %></span>
								</p>
							<% end %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/blogs/new.html.erb
<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<h3><%= link_to "Volver", blogs_path %></h3>
			<h1><%= @blog.title %></h1>
			<p><%= markdown(@blog.body) %></p>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<% @blog.comments.order(:created_at).each do |c| %>
					<table class="table table-bordered">
						<thead>
							<tr><th>
								<div><%= c.user.email %> comentó hace <%= time_ago(c.created_at) %></th></tr>
						</thead>
						<tbody>
							<tr><td><%= c.comment_body %></td></tr>
						</tbody>
					</table>
		<% end %>
		</div>
	</div>
</div>

<% if user_signed_in? %>
	<div class="container">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				Nuevo Comentario:
		      	<%= form_for Comment.new, :url => comments_path do |c| %>
		      		<div class="form-group">
		          		<%= c.text_field :comment_body, class: "form-control input-lg", placeholder: "Haz tu comentario" %>
		          	</div>
		          		<%= c.hidden_field :user_id, value: current_user.id %>
		          		<%= c.hidden_field :blog_id, value: @blog.id %>
		        	<div>
		        	  <%= c.submit "Comentar", class: "btn btn-primary btn-lg btn-block" %>
		        	</div>
		      	<% end %>
		    </div>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>SuperBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/blogs"><strong>SuperBlog</strong></a>
            <% if user_signed_in? %>
              <a class="navbar-brand" href="#"><strong>Usuario actual: <%= current_user.email %></strong></a>
            <% end %>
          </div>
          <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
            		<li><a href="#"><%= link_to "Nuevo Post", new_blog_path %> </a></li>
                <li><a href="#"><%= link_to "Salir", destroy_user_session_path, method: :delete %></a></li>
              <% else %>
            		<li><a href="#"><%= link_to "Ingresar", new_user_session_path %></a></li>
                <li><a href="#"><%= link_to "Registrarse", new_user_registration_path %></a></li>
              <% end %>
          </ul>
          
        </div>
      </nav>

          
    <% if flash[:notice] %>
      <p class="alert alert-info"><%= flash[:notice] %></p>
    <% end %>

  	<%= yield %>
    
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>